trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'mstest-sample\MSTestSample.sln'
    arguments: '--logger AzurePipelines'
    publishTestResults: false
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
