parameters:
- name: mergeTestResults
  displayName: Merge Test Results
  type: boolean
  default: false

trigger: none

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'nunit-sample\NUnitSample.sln'
    arguments: '--logger nunit -- NUnit.DisplayName=FullName'
    publishTestResults: false
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TestResults/TestResults.xml'
    mergeTestResults: ${{ parameters.mergeTestResults }}
  condition: succeededOrFailed()
